// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kC9VMjtYQSFFRSD-yXoo2wRXKwVZMi4',
    appId: '1:876427025263:web:0e9fa8cf989f2235b4a69a',
    messagingSenderId: '876427025263',
    projectId: 'uniapp-f826e',
    authDomain: 'uniapp-f826e.firebaseapp.com',
    storageBucket: 'uniapp-f826e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gTLfsD1qx6UKcpUONZE7SUJ_fJFMIKk',
    appId: '1:876427025263:android:a66311de933a9fccb4a69a',
    messagingSenderId: '876427025263',
    projectId: 'uniapp-f826e',
    storageBucket: 'uniapp-f826e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJ1OMxi8L6UFvsA6qQnvRoOYKnlWlKW4',
    appId: '1:876427025263:ios:05f710c94d606ec4b4a69a',
    messagingSenderId: '876427025263',
    projectId: 'uniapp-f826e',
    storageBucket: 'uniapp-f826e.firebasestorage.app',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJ1OMxi8L6UFvsA6qQnvRoOYKnlWlKW4',
    appId: '1:876427025263:ios:05f710c94d606ec4b4a69a',
    messagingSenderId: '876427025263',
    projectId: 'uniapp-f826e',
    storageBucket: 'uniapp-f826e.firebasestorage.app',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6kC9VMjtYQSFFRSD-yXoo2wRXKwVZMi4',
    appId: '1:876427025263:web:7f2423f76b38558bb4a69a',
    messagingSenderId: '876427025263',
    projectId: 'uniapp-f826e',
    authDomain: 'uniapp-f826e.firebaseapp.com',
    storageBucket: 'uniapp-f826e.firebasestorage.app',
  );
}
